Add 404 error handler to prevent Content-Security-Policy header being overwritten
taskcluster/taskcluster-lib-app pull request #20
Opened 2018-03-21 00:49 UTC by cecilydowns

I add a 404 error handler within createServer, since this is called at the bottom of the stack. This returns a JSON error message (in keeping with the rest of the app) and also prevents the Content-Security-Policy headers from being overwritten by the default 404 error message.

More information and discussion of the bug that this fixes can be found [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1421330).

2018-10-25 01:59 UTC, imbstack approved these changes
Ah, sorry I missed this 20 days ago! I should have seen it. This makes sense to me, I will land it tomorrow after playing around with it a bit!

2018-10-25 22:16 UTC, imbstack requested changes
Oh, actually it looks like there was already a 404 handler in here? You can see it tested in `test/app_test.js`. We can totally replace that with this though if you're still around? Sorry again for the delay. Happy to help whenever you have time.

2018-11-02 23:48 UTC, cecilydowns commented
@imbstack, could you point me to the line in `test/app_test.js` that you're referring to? I'm not seeing a 404 handler being tested.

Again, [this thread](https://bugzilla.mozilla.org/show_bug.cgi?id=1421330) on Bugzilla provides context for the changes I made here

2018-11-03 00:28 UTC, imbstack commented
Ah, sorry I should have mentioned where it is in src instead. [On these lines](https://github.com/taskcluster/taskcluster-lib-app/blob/d5c15db6a475ed7b0776ebe127b72f71830cc793/src/app.js#L146-L155) we optionally do a different 404 on `/`. I see that in the most recent master this has actually been removed so all you'll need to do is rebase! I can actually rebase this myself and see how it looks if you'd like? Thanks for this patch.

2018-11-03 00:33 UTC, imbstack reviewed
Next step would be to add a test that asserts you do in fact get a 404 when you try to access a resource that doesn't exist. Please let me know how else I can help.

2018-11-03 00:33 UTC, imbstack commented on src/app.js
> +  this.use(function(req, res, next) {
Let's make this use the `that` that is defined above!

2019-01-04 20:37 UTC, djmitche commented
bitrotten - we can surely re-open this against github.com/taskcluster/taskcluster later!

2019-01-04 20:37 UTC, closed without merging